--------------------------------------------------------
--  DDL for Tables
--------------------------------------------------------

  CREATE TABLE AT_CLIENT
   (
    "UUID" VARCHAR2(40) PRIMARY KEY,
	"JPAVERSION" INTEGER,
	"CREATED" TIMESTAMP (6),
	"CREATED_BY" VARCHAR2(50),
	"MODIFIED" TIMESTAMP (6),
	"MODIFIED_BY" VARCHAR2(50),
	
	"NAME" VARCHAR2(50),
	"DISPLAY_NAME" VARCHAR2(255),
	"DESCRIPTION" VARCHAR2(255),
	"ACTIVE" BOOLEAN
   );
   
   CREATE TABLE AT_ROLE
   (
    "UUID" VARCHAR2(40) PRIMARY KEY,
	"JPAVERSION" INTEGER,
	"CREATED" TIMESTAMP (6),
	"CREATED_BY" VARCHAR2(50),
	"MODIFIED" TIMESTAMP (6),
	"MODIFIED_BY" VARCHAR2(50),
	
	"NAME" VARCHAR2(50),
	"DISPLAY_NAME" VARCHAR2(255),
	"DESCRIPTION" VARCHAR2(255),
	"ACTIVE" BOOLEAN
   );
   
   CREATE TABLE AT_USER_GROUP
   (
    "UUID" VARCHAR2(40) PRIMARY KEY,
	"JPAVERSION" INTEGER,
	"CREATED" TIMESTAMP (6),
	"CREATED_BY" VARCHAR2(50),
	"MODIFIED" TIMESTAMP (6),
	"MODIFIED_BY" VARCHAR2(50),
	
	"NAME" VARCHAR2(50),
	"DISPLAY_NAME" VARCHAR2(255),
	"DESCRIPTION" VARCHAR2(255),
	"ACTIVE" BOOLEAN
   );
   
   CREATE TABLE AT_USERGROUPS_ROLES
   (
   	"USERGROUP_UUID" VARCHAR2(40),
   	"ROLE_UUID" VARCHAR2(40),
   );
   
   CREATE TABLE AT_USER
   (
    "UUID" VARCHAR2(40) PRIMARY KEY,
	"JPAVERSION" INTEGER,
	"CREATED" TIMESTAMP (6),
	"CREATED_BY" VARCHAR2(50),
	"MODIFIED" TIMESTAMP (6),
	"MODIFIED_BY" VARCHAR2(50),
	
	"USERNAME" VARCHAR2(50),
	"PASSWORD" VARCHAR2(255),
	"PASSWORD_DATE" TIMESTAMP (6),
	"PWD_LINK_CREATED" TIMESTAMP (6),
	"PWD_LINK_HASH" VARCHAR2(255),
	
	"ACC_EXP_SINCE" TIMESTAMP (6),
	"ACC_LOCK_SINCE" TIMESTAMP (6),
	"ACC_NON_EXP" BOOLEAN,
	"ACC_NON_LOCK" BOOLEAN,
	"CRED_EXP_SINCE" TIMESTAMP (6),
	"CRED_NON_EXP" BOOLEAN,
	
	"FIRSTNAME" VARCHAR2(255),
	"LASTNAME" VARCHAR2(255),
	"EMAIL" VARCHAR2(255),
	"PHONE" VARCHAR2(255),
	"LOCALE" VARCHAR2(5),
	"TIMEZONE" VARCHAR2(100),
	
	"LAST_LOGIN"  TIMESTAMP (6),
	"LAST_LOGIN_ATTEMPT" TIMESTAMP (6),
	"LOGIN_ATTEMPTS" INTEGER
	
   );

   CREATE TABLE AT_USER_USERGROUPS
   (
   	"USER_UUID" VARCHAR2(40),
   	"USERGROUP_UUID" VARCHAR2(40),
   );
   
   CREATE TABLE AT_USER_CLIENTS
   (
   	"USER_UUID" VARCHAR2(40),
   	"CLIENT_UUID" VARCHAR2(40),
   );

--------------------------------------------------------
--  Ref Constraints
--------------------------------------------------------

  ALTER TABLE AT_USER_CLIENTS ADD FOREIGN KEY ("USER_UUID") REFERENCES AT_USER ("UUID") ON DELETE CASCADE;
  ALTER TABLE AT_USER_CLIENTS ADD FOREIGN KEY ("CLIENT_UUID") REFERENCES AT_CLIENT ("UUID") ON DELETE CASCADE;
  
  ALTER TABLE AT_USER_USERGROUPS ADD FOREIGN KEY ("USER_UUID") REFERENCES AT_USER ("UUID") ON DELETE CASCADE;
  ALTER TABLE AT_USER_USERGROUPS ADD FOREIGN KEY ("USERGROUP_UUID") REFERENCES AT_USER_GROUP ("UUID") ON DELETE CASCADE;
  
  ALTER TABLE AT_USERGROUPS_ROLES ADD FOREIGN KEY ("USERGROUP_UUID") REFERENCES AT_USER_GROUP ("UUID") ON DELETE CASCADE;
  ALTER TABLE AT_USERGROUPS_ROLES ADD FOREIGN KEY ("ROLE_UUID") REFERENCES AT_ROLE ("UUID") ON DELETE CASCADE;



